name: Build and Deploy Console

on:
    push:
        branches: ["maalsi24"]
        paths:
            - 'RabbitMqProduct.ConsoleApplication/**'
    workflow_dispatch:

env: 
    workdir: "RabbitMqProduct.ConsoleApplication"
    dockerregistry: ${{ secrets.DOCKER_HOSTNAME }}
    IMAGE_NAME: "ttruvelot_pubsub-console"
jobs:

  deploy-console:
    permissions:
      contents: read
      packages: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          enable-AzPSSession: true
      - uses: mr-smithers-excellent/docker-build-push@v6
        name: Build & Push image
        with:
          image: ${{ env.dockerregistry }}/${{ env.IMAGE_NAME }}
          tags: "latest"
          dockerfile: ${{ env.workdir }}/Dockerfile
          directory: ${{ env.workdir }}
          registry: ${{ env.dockerregistry }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          

          
    
    
        

